import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          backgroundColor: "rgba(9, 132, 214, 1)",
          minHeight: "100vh",
          width: "100vw",
          display: "grid",
          placeItems: "center",
          padding: "30px 9vw"
        }}
      >
        <div
          style={{
            backgroundColor: "#F5F5F5",
            padding: "34px 6vw",
            borderRadius: 20,
            width: "100%",
            maxWidth: 600
          }}
        >
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              marginBottom: 31
            }}
          >
            <div style={{ marginBottom: 31 }}>
              <Image src="/images/logo-ima.svg" width={210} height={75} />
            </div>
            <h2
              style={{
                fontSize: 30,
                fontWeight: "700",
                fontFamily: "inter",
                marginBottom: 50
              }}
            >
              Welcome to Admin
            </h2>
            <h1
              style={{
                fontSize: 20,
                fontWeight: "700",
                fontFamily: "inter"
              }}
            >
              Login
            </h1>
          </div>
          <form
            style={{ marginBottom: 40 }}
            onSubmit={(e) => {
              e.preventDefault();
            }}
          >
            <div style={{ marginBottom: 48 }}>
              <input
                type="email"
                placeholder="Email Address"
                style={{
                  width: "100%",
                  padding: "14px 21px",
                  borderRadius: 50,
                  backgroundColor: "rgba(251, 251, 251, 1)",
                  border: "1px solid rgba(217, 217, 217, 1)"
                }}
              />
            </div>

            <div style={{ marginBottom: 40 }}>
              <input
                type="password"
                placeholder="Password"
                style={{
                  width: "100%",
                  padding: "14px 21px",
                  borderRadius: 50,
                  backgroundColor: "rgba(251, 251, 251, 1)",
                  border: "1px solid rgba(217, 217, 217, 1)"
                }}
              />
            </div>
            <button
              onAbort={(e) => {
                e.preventDefault();
                router.push("/profile");
              }}
              style={{
                padding: "14px 21px",
                width: "100%",
                backgroundColor: "rgba(9, 132, 214, 1)",
                color: "#fff",
                border: "1px solid rgba(9, 132, 214, 1)",
                borderRadius: 50
              }}
            >
              Login
            </button>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
